stages:
  - build
  - test
  - deploy

build data pipeline:
  stage: build
  script:
    - echo "Building data pipeline..."
    - echo "Compiling the code..."
    - touch ./env && cat $ENV > ./env
    - cat ./env
    - echo
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - scp -o StrictHostKeyChecking=no ./env $SERVER:$DIR #Overwrite env file
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && git checkout main && git pull && make build"
    - echo "Compile complete."

unit test data pipeline:
  stage: test
  script:
    - echo "Running unit test... This step will take about 60 seconds."
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && make up && make test && make down"
    - echo "Test complete."

lint test code base:
  stage: test
  script:
    - echo "Linting code... This step will take about 10 seconds."
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && make install"
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && . venv/bin/activate && make check && make lint"
    - echo "Lint complete."

deploy to production:
  stage: deploy
  when: manual
  allow_failure: false
  script:
    - echo "Delpoying to production..."
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && git checkout main && git checkout -- env && git pull && make build" # Update new code and build
    - touch ./env && cat $ENV > ./env # Load env from $ENV
    - scp -o StrictHostKeyChecking=no ./env $SERVER:$DIR #Overwrite env file
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && make restart"
    - echo "Data pipeline successfully deployed."

smoke test production:
  stage: test
  script:
    - echo "Running smoke test... This will take about 60 seconds."
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && nc -zv localhost 3306" # health check MySQL
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && nc -zv localhost 5432" # health check PostgreSQL
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && curl http://localhost:3001/" # health check dagit
    - ssh -o StrictHostKeyChecking=no $SERVER "cd $DIR && curl http://localhost:3000/" # health check metabase
    - echo "Smoking complete."
