version: "3.9"

services:
  de_mysql:
    image: mysql:8.0
    container_name: de_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql-data:/var/lib/mysql
      - ./dataset:/tmp/dataset
      - ./load_dataset/mysql_datasource.sql:/tmp/mysql_datasource.sql
      - ./load_dataset/mysql_load_csv.sql:/tmp/mysql_load_csv.sql
      - ./load_dataset/mysql_set_foreign_key.sql:/tmp/mysql_set_foreign_key.sql
    env_file:
      - env
    networks:
      - de_network

  de_psql:
    image: postgres:15
    container_name: de_psql
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
      - ./load_dataset/psql_datasource.sql:/tmp/psql_datasource.sql
    env_file:
      - env
    networks:
      - de_network

  de_metabase:
    image: metabase/metabase:v0.45.0
    container_name: de_metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    env_file:
      - env
    networks:
      - de_network

  elt_pipeline:
    build:
      context: ./elt_pipeline
    image: elt_pipeline:latest
    container_name: elt_pipeline
    volumes:
      - ./elt_pipeline:/opt/dagster/app
    env_file:
      - env
    networks:
      - de_network

  dbt_analytics:
    build:
      context: ./dbt_analytics
    image: dbt_analytics
    container_name: dbt_analytics
    volumes:
      - ./dbt_analytics:/opt/dagster/app
    env_file:
      - env
    networks:
      - de_network

  de_dagster_dagit:
    build:
      context: ./dockers/dagster
    image: de_dagster:latest
    container_name: de_dagster_dagit
    expose:
      - "3001"
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "3001"
      - -w
      - workspace.yaml
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - env
    networks:
      - de_network

  de_dagster_daemon:
    build:
      context: ./dockers/dagster
    image: de_dagster:latest
    container_name: de_dagster_daemon
    entrypoint:
      - dagster-daemon
      - run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dagster_home:/opt/dagster/dagster_home
    env_file:
      - env
    networks:
      - de_network

networks:
  de_network:
    driver: bridge
    name: de_network
