name: "spotify"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "spotify"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# using the `{{ config(...) }}` macro.
models:
  spotify:
    # Config indicated by + and applies to all files under models/example/
    analytics:
      +materialized: table
